### ISSUE TITLE
Android / iOS support?

### ISSUE THREAD

**Issue by brentpicasso** [matham/filers#1]
Hello! Great work on this package. What does android or iOS support look like? If not supported, roughly what would be needed to make it work?

**Comment by matham** [comment]
Which parts specifically of filers are you referring to? 

For example, the video acquisition parts uses ffmpeg, which you'd need to compile for android and iOS. It has been done for iOS I believe. The compression part using ffmpeg, again, you'd need a compiled ffmpeg binary.

**Comment by brentpicasso** [comment]
Hi, Sorry for the late reply.

Your point rings true - if the libraries can be compiled it should work in theory. If you're planning to test it on Android or IOS let me know. Correspondingly, If you are interested / available for consulting work to get this implemented and tested on either of these platforms, please contact me at brent@autosportlabs.com . 

Thanks again for your open source contribution - this stuff makes a difference.
